### ISSUE TITLE
Loggable + Other annotations

### ISSUE THREAD

**Issue by arcanefoam** [fikovnik/ttc15-tranj-case#1]
From the example it seems that Loggable annotation works in combination of the other two. So basically, there is a behaviour when used alone, and additional behaviour when used in combination with the other annotations. Can you confirm this?

**Comment by fikovnik** [comment]
No, it always works the same, it logs the entry and all exists points of a method. However, the `@RetryOnFailure` might add additional catch branches which in turn adds more exit points. That is why, there is the rule which says that `@Loggable` should be applied the last shall there be more than annotation applied on a method.

**Comment by arcanefoam** [comment]
But looking at the example (ManualURLDownload.java) it seems that for the try the messages of the loogger are specific to the Retry, and in one case the log is created as a warning rather than an trace (when the timeout is interrupted), and there is also additional logging of the retry counter. This behaviour is additional to the "normal" loggable annotation definition.

**Comment by fikovnik** [comment]
You should considered the `SynthesizedURLDownload`. At some point the idea was to have one more task in which the annotation transformation would be context sensitive, i.e. the annotations would know about one another, but it has been dropped to simplify the case study.
