### ISSUE TITLE
Loggable skipArgs attribute

### ISSUE THREAD

**Issue by arcanefoam** [fikovnik/ttc15-tranj-case#2]
Can you provide further explanation of this option? From the documentation I would assume the logger logs the values of the method parameters either on entry, exit or both. When the annotation is at the class level, is the logging done on the class fields as opposed to the method fields?

When the annotation is done at the method level, if skipArgs is false (the default) then the class fields are logged?

**Comment by fikovnik** [comment]
To simplify things, we only consider methods. The `skipArgs` should turn on / off logging of method argument values and instance fields. I should been more specific, it should be just instance fields not class fields.

**Comment by arcanefoam** [comment]
When does the logging occur? Arguments values on entry and instance fields on entry/exit?

**Comment by fikovnik** [comment]
The logging occur on a method entry point and on all method exit points (both successful and exceptional). The arguments values only at the entry.
